services:

  backend:
    build:
      context: ./backend
    ports:
      - "5182:5182"
    environment:
      - ASPNETCORE_URLS=http://+:5182
    restart: always  # 👉 auto start when server restarts

