services:
  backend:
    build:
      context: ./backend
    ports:
      - "5182:5182"
    environment:
      - ASPNETCORE_URLS=http://+:5182
    env_file:
      - ./backend/.env  
    restart: always
    mem_limit: 512m
    networks:
      - host-bridge

networks:
  host-bridge:
    external: true
    name: bridge  # 👈 sử dụng đúng tên network mặc định của Docker
