services:

  backend:
    build:
      context: ./backend
    ports:
      - "5182:5182"
    environment:
      - ASPNETCORE_URLS=http://+:5182
    env_file:
      - ./backend/.env  
    restart: always  # 👉 auto start when server restarts
    mem_limit: 512m

