- name: 🚀 SSH to VPS and deploy
  env:
    VPS_IP: ${{ secrets.VPS_IP }}
    VPS_USER: ${{ secrets.VPS_USER }}
    # ... các biến khác ...
  run: |
    ssh $VPS_USER@$VPS_IP bash -s <<EOF
      export APP_BASE_URL="$APP_BASE_URL"
      export JWT_KEY="$JWT_KEY"
      export JWT_ISSUER="$JWT_ISSUER"
      export JWT_AUDIENCE="$JWT_AUDIENCE"
      export DB_CONNECTION="$DB_CONNECTION"
      export REDIS_CONNECTION="$REDIS_CONNECTION"
      export EMAIL_FROM="$EMAIL_FROM"
      export EMAIL_USERNAME="$EMAIL_USERNAME"
      export EMAIL_PASSWORD="$EMAIL_PASSWORD"
      export EMAIL_PORT="$EMAIL_PORT"
      export EMAIL_SMTP="$EMAIL_SMTP"
      export GOOGLE_CLIENT_ID="$GOOGLE_CLIENT_ID"
      export GOOGLE_CLIENT_SECRET="$GOOGLE_CLIENT_SECRET"

      set -e

      echo "📁 Kiểm tra thư mục /root/deploy"
      if [ ! -d "/root/deploy/.git" ]; then
        git clone https://github.com/chuong2610/deploy.git /root/deploy
      fi

      cd /root/deploy
      git fetch origin
      git reset --hard origin/main

      echo "📝 Ghi vào backend/.env"
      rm -f /root/deploy/backend/.env
      cat <<EOT > /root/deploy/backend/.env
APP_BASE_URL=$APP_BASE_URL
JWT_KEY=$JWT_KEY
JWT_ISSUER=$JWT_ISSUER
JWT_AUDIENCE=$JWT_AUDIENCE
DB_CONNECTION=$DB_CONNECTION
REDIS_CONNECTION=$REDIS_CONNECTION
EMAIL_FROM=$EMAIL_FROM
EMAIL_USERNAME=$EMAIL_USERNAME
EMAIL_PASSWORD=$EMAIL_PASSWORD
EMAIL_PORT=$EMAIL_PORT
EMAIL_SMTP=$EMAIL_SMTP
GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID
GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET
EOT

      echo "♻️ Dừng container cũ nếu có"
      docker compose down || true

      echo "🚀 Build và chạy lại container"
      docker compose up -d --build

      echo "🧹 Xoá image không dùng"
      docker image prune -f

      echo "✅ Triển khai hoàn tất!"
    EOF
